### ISSUE TITLE
Runtime error - more information on versions of different components required

### ISSUE THREAD

**Issue by victornicolet** [Herbping/WTAlib#3]
After following the setup steps described in the README, the last command yields the following error:
```
java -cp .:/usr/local/lib/antlr-4.9.2-complete.jar:../../../lib/CVC4-1.8.0.jar:../../..lib/com.microsoft.z3.jar -ea -Djava.library.path="$LD_LIBRARY_PATH:../../../lib" SLMain ../../../benchmarks/CLIA_Track_PLUS_Pos/mpg_guard1/ 1 1

Exception in thread "main" java.lang.UnsatisfiedLinkError: edu.nyu.acsys.CVC4.CVC4JNI.ExprManager_DATATYPE_FLAG_NONE_get()I
	at edu.nyu.acsys.CVC4.CVC4JNI.ExprManager_DATATYPE_FLAG_NONE_get(Native Method)
	at edu.nyu.acsys.CVC4.ExprManager.<clinit>(ExprManager.java:411)
	at SLMain.main(SLMain.java:39)
```
This problem might be solvable if the exact versions of each of the components required are provided.
For example, there seems to be conflicting versions of antlr4 used in the java and python parts of the code (using 4.9.2 in the NayHorn commands yields errors, but NaySL requires 4.9.2).

**Comment by qinheping** [comment]
Hi,

I updated the instructions with the exact versions of each of the required components. Please check if the new instructions work for you. I also got the warning saying that the ANTLR tool version does not match the ANTLR code generation though the tool works as expected. Recompiling the `.g4` files in `src/main/java/parser` and `src/main/python/parser` on your machine will resolve the warning.
